### ISSUE TITLE
play-angular-standalone doesn't compile

### ISSUE THREAD

**Issue by KannarFr** [jwt-scala/jwt-scala#135]
Hi,

`play-angular-standalone` example does not compile using `jwt-play` v3.1.0.

**Comment by KannarFr** [comment]
```
jwt-scala/examples/play-angular-standalone/app/controllers/Secured.scala:20:13: value jwtSession is not a member of play.api.mvc.Request[A]
         [error]     request.jwtSession.getAs[User]("user") match {
```

**Comment by pauldijou** [comment]
Unfortunately, I barely have time (and motivation) to maintain the lib itself, I will rely on the community and pull requests for updating those examples. If you would have time to open one, that would be awesome!

**Comment by pauldijou** [comment]
Fixed

**Comment by KannarFr** [comment]
@pauldijou tanks.
