### ISSUE TITLE
Runtime error with latest version of upickle

### ISSUE THREAD

**Issue by Voltir** [jwt-scala/jwt-scala#171]
Using upickle version 1.2.0 as provided by the jwt-upickle dependency generates the following runtime error:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Object upickle.default$.read(ujson.Readable, upickle.core.Types$Reader)'
	at pdi.jwt.JwtUpickle$.parseHeader(JwtUpickle.scala:27)
	at pdi.jwt.JwtUpickle$.parseHeader(JwtUpickle.scala:25)
	at pdi.jwt.JwtCore.$anonfun$decodeAll$1(Jwt.scala:373)
...
```
I think this code would have worked with upickle version 0.9.5, but im not sure what changed between that version and the latest version.

**Comment by Voltir** [comment]
I did some more testing and I think this is due to a dependency conflict with another library included in my project - sorry for the noise.

**Comment by Voltir** [comment]
@pauldijou Ok, so I thought this library transitively depended on upickle 1.2.2 but, according to maven, jwt-scala version 4.3.0 still depends on upickle version 0.9.5. I guess that 4.3.0 was published and then the upickle dependency was updated, but the next version has yet to be published. 
I don't suppose you are planning on cutting on 4.4.0 any time soon
