### ISSUE TITLE
Doesn't work with Play 2.7.x

### ISSUE THREAD

**Issue by patientplatypus** [jwt-scala/jwt-scala#153]
Following the examples from here: http://pauldijou.fr/jwt-scala/samples/jwt-play/ I took an existing, running, response and did the following

```
 Ok(responseVal)
          .withJwtSession(("id", 1), ("key", "value"))
```

where I had imported `import pdi.jwt.JwtSession._` at the top of the file.

I also included the library in my `build.sbt` file as `"com.pauldijou" %% "jwt-play" % "4.2.0"` as directed.

The error I got was the following: 

```
[error] /Users/patientplatypus/Documents/platypusNEST/the_daily_blech/scala_blech_blog/blog/app/controllers/PostController.scala:635:12: value withJwtSession is not a member of play.api.mvc.Result
[error] possible cause: maybe a semicolon is missing before `value withJwtSession`?
[error]           .withJwtSession(("id", 1), ("key", "value"))
[error]            ^
``` 

I don't know why but this library doesn't work.

**Comment by patientplatypus** [comment]
I've also tried mimicing the example from here: https://github.com/pauldijou/jwt-scala/blob/master/examples/play-angular/app/controllers/Application.scala which has the line `Ok.addingToJwtSession("user", User(username))`, but that again results in

```
[error] /Users/patientplatypus/Documents/platypusNEST/the_daily_blech/scala_blech_blog/blog/app/controllers/PostController.scala:635:12: value addingToJwtSession is not a member of play.api.mvc.Result
[error] possible cause: maybe a semicolon is missing before `value addingToJwtSession`?
[error]           .addingToJwtSession(("key2", "value2"), ("key3", "value3"))
[error]            ^
```

How is this library supposed to work?

**Comment by patientplatypus** [comment]
Here is my entire function that uses the jwt handler. The warning about the semi-colon is just because the result and the `addingToJwtSession` were on separate lines, but on a single line it also errors.

```
def admin_login: Action[AnyContent] = Action.async {request: Request[AnyContent] =>
    Future {
      val body: AnyContent          = request.body
      val jsonBody: Option[JsValue] = body.asJson
      println("inside admin_login")
      jsonBody
      .map { json =>
        var returnVal:Future[String] = admin.login(json);
        val result = Await.result(returnVal, 3.second)
        println("value of result")
        println(result)
        var responseVal = new Response().standard_response("/admin/login", result)
        println("value of responseVal: ")
        println(responseVal)
        println("value of responseVal.msg: ")
        var responseValMsg:String = Json.stringify((responseVal \ "msg").get)
        responseValMsg = responseValMsg.substring(1, responseValMsg.length()-1);
        println(responseValMsg)
        if(responseValMsg=="passwords_match"){
          Ok(responseVal)
          .withSession("access_rights"->"admin")
          // .addingToJwtSession(("key2", "value2"), ("key3", "value3")) //DOESNT WORK
          // .withJwtSession(("id", 1), ("key", "value")) //DOESNT WORK
        }else{
          Ok(responseVal)
          .withSession("access_rights"->"no_access")
          // .withJwtSession(("id", 1), ("key", "value"))
        }       
      }
      .getOrElse {
        BadRequest("Expecting application/json request body")
      }
    }(ec)
  }
```

**Comment by patientplatypus** [comment]
I've tried to work around suggested here (https://github.com/pauldijou/jwt-scala/issues/19) and that didn't work either. Note, in the above I have also tried ` Ok(responseVal).withJwtSession(("id", 1), ("key", "value"))` and 

```
          var response = Ok(responseVal).JwtSession
          println("value of response")
          println(response)
```

**Comment by pauldijou** [comment]
Could you [try that](https://github.com/pauldijou/jwt-scala/issues/140#issuecomment-524822869)?

**Comment by alternegro** [comment]
In Play 2.8, even with both clock and conf implicit in scope, using `withJwtSession` still throws `value withJwtSession is not a member of play.api.mvc.Result`.

**Comment by alternegro** [comment]
@patientplatypus did you get it to work? I have the clock and configuration implicit in scope yet I still see the `value withJwtSession is not a member of play.api.mvc.Result` error. Thanks
