### ISSUE TITLE
Play 2.5.x support

### ISSUE THREAD

**Issue by omainegra** [jwt-scala/jwt-scala#15]
Running example app _play-angular-standalone_ with `play-2.5.0` throws the Exception

``` scala
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoSuchMethodError: play.api.libs.json.JsLookup$.$bslash$extension(Lplay/api/libs/json/JsLookupResult;Ljava/lang/String;)Lplay/api/libs/json/JsLookupResult;]]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
    at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
    at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
    at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
    at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: play.api.libs.json.JsLookup$.$bslash$extension(Lplay/api/libs/json/JsLookupResult;Ljava/lang/String;)Lplay/api/libs/json/JsLookupResult;
    at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:463)
    at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
    at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
    at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
    at scala.Option.map(Option.scala:146)
    at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
    at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
Caused by: java.lang.NoSuchMethodError: play.api.libs.json.JsLookup$.$bslash$extension(Lplay/api/libs/json/JsLookupResult;Ljava/lang/String;)Lplay/api/libs/json/JsLookupResult;
    at pdi.jwt.JwtJson$.getAlgorithm(JwtJson.scala:19)
    at pdi.jwt.JwtJson$.getAlgorithm(JwtJson.scala:14)
    at pdi.jwt.JwtJsonCommon$class.encode(JwtJsonCommon.scala:24)
    at pdi.jwt.JwtJson$.encode(JwtJson.scala:14)
    at pdi.jwt.JwtSession.serialize(JwtSession.scala:61)
    at pdi.jwt.JwtPlayImplicits$RichResult.withJwtSession(JwtPlayImplicits.scala:61)
    at pdi.jwt.JwtPlayImplicits$RichResult.addingToJwtSession(JwtPlayImplicits.scala:82)
    at controllers.Application$$anonfun$login$1$$anonfun$apply$2.apply(Application.scala:30)
    at controllers.Application$$anonfun$login$1$$anonfun$apply$2.apply(Application.scala:28)
    at play.api.libs.json.JsResult$class.fold(JsResult.scala:72)
```

**Comment by rschanafelt** [comment]
I'm getting the same error running play 2.5.0 as well. FYI, the error appears to exist in both 0.5.0 and 0.5.1.

It occurs when invoking `JwtJson.decodeAll(...)` with the **jwt-play-json** library.

As a workaround, you can try swapping the **jwt-play-json** library for one of the others. (I was able to get my app working with **jwt-circe** on v0.5.1).

**Comment by pauldijou** [comment]
Yeah, I only had time to fix the JSON stringify in 0.5.1. I took a quick look at the problem yesterday but couldn't figure what is going wrong. Tests are using those methods and are all green. But when running the app, it crashes. Need more time...

**Comment by omainegra** [comment]
After updating dependencies (including sbt) and some minor changes it is working for me. I did a pull request.

**Comment by pauldijou** [comment]
It has been released in 0.6.0 ( https://repo1.maven.org/maven2/com/pauldijou/jwt-play_2.11/0.6.0/ ) by the way. Sorry it took so long but Play not supporting Scala 2.10 anymore kind of break my cross-version build the hard way.

**Comment by axiopisty** [comment]
I'm just getting my feet wet with sbt/play/scala. I'm following the [iheartradio play swagger](http://iheartradio.github.io/play-swagger/) tutorial except I didn't clone their project. Instead I used `activator new play-swagger-tutorial play-scala` to create my own. This creates a play 2.5 application.

The only other modification from that tutorial that I made was in the version of swagger-ui:

```
libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  "com.iheart" %% "play-swagger" % "0.1.9",
  "org.webjars" % "swagger-ui" % "2.1.8-M1",
  "org.webjars" % "bootstrap" % "3.3.6",
  "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.0-RC1" % Test
)

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

resolvers += Resolver.jcenterRepo
```

It looks like I did everything right but when I try to hit the swagger-ui page I get the error discussed in this thread:

```
Caused by: java.lang.NoSuchMethodError: play.api.libs.json.JsLookup$.$bslash$extension(Lplay/api/libs/json/JsLookupResult;Ljava/lang/String;)Lplay/api/libs/json/JsLookupResult;
    at com.iheart.playSwagger.SwaggerSpecGenerator.endPointSpec$1(SwaggerSpecGenerator.scala:195)
    at com.iheart.playSwagger.SwaggerSpecGenerator.com$iheart$playSwagger$SwaggerSpecGenerator$$endPointEntry$1(SwaggerSpecGenerator.scala:224)
    at com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$paths$1.apply(SwaggerSpecGenerator.scala:230)
    at com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$paths$1.apply(SwaggerSpecGenerator.scala:230)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
    at scala.collection.immutable.List.flatMap(List.scala:344)
    at com.iheart.playSwagger.SwaggerSpecGenerator.paths(SwaggerSpecGenerator.scala:230)
```

I don't know enough about sbt yet to know how to follow your workaround:

> try swapping the jwt-play-json library for one of the others. (I was able to get my app working with jwt-circe on v0.5.1)

Would you provide an example how I could swap the library?

**Comment by pauldijou** [comment]
@axiopisty You can check the diff which solve the problem here : https://github.com/pauldijou/jwt-scala/pull/16/files

Looks like it was the way to import and use the Play plugin in build.sbt which caused the issue.

**Comment by rschanafelt** [comment]
Hi @axiopisty, I don't see where you're using the jwt-scala library in your application. Are you sure you're having a jwt-scala issue or is it a general issue with Play and the iheartradio tutorial? Perhaps you could direct your question to StackOverflow as it might be a better venue for general questions than this closed issue?

**Comment by alex88** [comment]
I've the same issue here with play 2.4.6, but I've just included `jwt-play` 0.7.0, maybe I also need to include the json library

**Comment by alex88** [comment]
Oh nevermind, I've downgraded to 0.5.1 and it works fine, thanks ;)

**Comment by tabkram** [comment]
same problem,
I get this Error: `Method threw 'java.lang.NoSuchMethodError' exception.`
on method `Ok.addingToJwtSession("user", Json.toJson(authUser.get))`

with version : **0.7.0** and **0.8.0** and scala **2.11.7**
**I've downgraded to 0.5.1**  to fix that
