### ISSUE TITLE
Update json4s to 3.5.0

### ISSUE THREAD

**Issue by sanllanta** [jwt-scala/jwt-scala#33]
Hi,

I am using json4s in my project along with jwt-scala. It worked ok with version 3.4.2 but today I updated to 3.5.0 and got this exeption:

`java.lang.NoSuchMethodError:
org.json4s.native.JsonMethods$.render(Lorg/json4s/JsonAST$JValue;Lorg/json4s/Formats;)Lscala/text/Document;`

I reverted to 3.4.2 and have no rush to update to 3.5.0, but it would be nice to have the latest version. Specially since the current one referenced in jwt-scala is 3.3.0.

**Comment by pauldijou** [comment]
If you could provide a PR, that would be super great. Otherwise, I will do it asap but I don't have much time to dive back into Scala at the moment.

**Comment by sanllanta** [comment]
I'm on it

**Comment by sanllanta** [comment]
#34 Done. Ran tests and it seems to be working OK.

**Comment by pauldijou** [comment]
Fixed in 0.9.1

**Comment by sanllanta** [comment]
Nice. Thank you!
