### ISSUE TITLE
json4s version for use with jwt-json4s-native

### ISSUE THREAD

**Issue by alathon** [jwt-scala/jwt-scala#10]
Hi,

It seems that if you include the newest version of json4s (3.3.0), this will cause problems with render() and the like. I couldn't see a version to use mentioned anywhere; but inspecting jwt-scala it seems you use 2.10 -> You may want to mention that somewhere =)

**Comment by pauldijou** [comment]
I'm not a big user of json4s so I'm not sure what you're talking about... What is that "render()" stuff? Currently using [3.2.10](https://github.com/pauldijou/jwt-scala/blob/master/project%2FDependencies.scala#L6), can update if necessary.

**Comment by alathon** [comment]
Initially when using jwt-json4s-native, I also added a json4s dependency on the most recent version (3.3.0) to my project (so I could do some path manipulation etc); this, however, does not seem to play well with the current version of jwt-json4s-native -- JwtJson4s.decode(token, key, algorithms) throws the following at me:

java.lang.NoSuchMethodError: org.json4s.native.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;
    at pdi.jwt.JwtJson4s$.parse(JwtJson4sNative.scala:16)
    at pdi.jwt.JwtJson4s$.parseHeader(JwtJson4sNative.scala:25)
    at pdi.jwt.JwtJson4s$.parseHeader(JwtJson4sNative.scala:15)
    at pdi.jwt.JwtCore$$anonfun$decodeAll$2.apply(Jwt.scala:374)
    at pdi.jwt.JwtCore$$anonfun$decodeAll$2.apply(Jwt.scala:372)
    at scala.util.Try$.apply(Try.scala:192)
    at pdi.jwt.JwtCore$class.decodeAll(Jwt.scala:372)
    at pdi.jwt.JwtJson4s$.decodeAll(JwtJson4sNative.scala:15)
    at pdi.jwt.JwtCore$class.decode(Jwt.scala:452)
    at pdi.jwt.JwtJson4s$.decode(JwtJson4sNative.scala:15)
    at ...

The same exact code works fine using 3.2.10. I don't necessarily see a reason to update to 3.3.0 per se, this was mostly to note that since there seems to be a compatability issue with 3.3.0, you may want to explicitly note the version used in the examples section of the documentation for jwt-json4s-native :)

**Comment by pauldijou** [comment]
Okay, I didn't fully understand why there was such a breaking change on a minor release of json4s but I updated the version to 3.3.0 and should have fixed everything.
