### ISSUE TITLE
example 2.12.x in play 2.6.x ?

### ISSUE THREAD

**Issue by sugondonababan** [jwt-scala/jwt-scala#70]
```
import pdi.jwt.JwtSession._
...
val session = request.jwtSession.getAs[Obj]("name")
```

error:
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class pdi.jwt.JwtSession$]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)

**Comment by pauldijou** [comment]
I updated all examples to work with Play 2.6.6 and Scala 2.12.4. Do tell me if it fixes your issue.

**Comment by sugondonababan** [comment]
Sorry response late,
All running well after scalaVersion := "2.12.4" changed
Thanks...
